In [1]:

import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd

### loading datasets
1. the parameters are obtained through least squares:
    e = tx + aX-bY
    n = ty + bX+aY

In [2]:
inputs = pd.read_csv('data/bursa1.csv',delimiter=',', header=None) #loading inputs from a different file 
print (inputs.shape)
targets = pd.read_csv('data/UTM1.csv',delimiter=',', header=None) # loading targets
print(targets.shape)
trains = pd.read_csv('data/Cass_f1.csv',delimiter=',', header=None) #loading inputs from a different file 
print (trains.shape)
trains_labels = pd.read_csv('data/utm_test1.csv',delimiter=',', header=None) # loading targets
print (trains_labels.shape)

test = pd.read_csv('data/Xtest.csv',delimiter=',', header=None) # loading targets
print(test.shape)


labels = pd.read_csv('data/yTest.csv',delimiter=',', header=None) # loading targets
print(labels.shape)

(64, 4)
(64, 1)
(16, 2)
(16, 2)
(17, 2)
(17, 2)


In [3]:
inputs

0            1  2  3
0  -12402.00720  56075.00088  1  0
1  -56075.00088 -12402.00720  0  1
2  -12235.34256  63650.40864  1  0
3  -63650.40864 -12235.34256  0  1
4  -12378.14136  58437.99336  1  0
..          ...          ... .. ..
59 -55883.12928 -14778.01464  0  1
60 -10426.38504  59028.81768  1  0
61 -59028.81768 -10426.38504  0  1
62 -14167.16496  65094.58152  1  0
63 -65094.58152 -14167.16496  0  1

[64 rows x 4 columns]

In [3]:

bursa= inputs.to_numpy()
EnUTM = targets.to_numpy()
print (type(bursa))
print (type(inputs))
print (type(EnUTM))
print (EnUTM.shape)

<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
(64, 1)


In [4]:
A=bursa
At=A.T
At.shape
ATA = np.dot(At,A)
ATA
L = EnUTM
L.shape
ATL= np.dot(At,L)
ATL.shape

(4, 1)

In [5]:
from numpy.linalg import inv
m_inv=inv(ATA)*-1
m_inv
x1= -(np.dot(m_inv,ATL))
x1

array([[1.00025386e+00],
       [1.80432323e-04],
       [2.77492392e+05],
       [1.00001873e+07]])

In [6]:
a =x1[0]
a
b = x1[1]
b
c=x1[2]
d = x1[3]


In [7]:
t = trains.to_numpy()
t1 = t[:,0]*a

t2 = t[:,1]*b

t3 =  t[:,0]*b

t4 =  t[:,1]*a

In [8]:
east = c+ t1-t2

print (east)
north= d +t3+t4

print (north)

[262058.36287359 266951.82689545 263425.60794996 261269.93451256
 266421.80675213 267141.15427161 267293.43874466 265739.35058532
 265088.31011368 265445.32199025 263168.06739581 267272.86036401
 262157.24567385 261519.3563422  262644.33761799 263424.94570212]
[9940059.71023834 9936008.62005988 9941625.44127057 9934567.87264495
 9933929.50458342 9943791.4421609  9943294.27559052 9941300.34105396
 9934062.16009098 9933383.56743074 9939149.15020005 9934500.90685945
 9939322.32114288 9937093.97921577 9944958.82967419 9944789.67207315]


In [9]:
ene1 = pd.DataFrame(east)
ene1.shape
#type(ene1)
ene2 = pd.DataFrame(north)
ene2.shape

(16, 1)

In [10]:
m =ene1.join(ene2, on= None, how ='right', lsuffix = '_left', rsuffix = '_right')
m.to_csv('y.csv', header=False, index=False)

In [11]:
ene = pd.read_csv('y.csv',delimiter=',', header=None, ) # loading targets
print(ene.shape)

(16, 2)


In [12]:
enen =ene.to_numpy()

In [13]:
type(enen)
error = trains_labels - enen
error

0         1
0  -0.062874 -0.410238
1   0.673105  0.479940
2  -0.307950 -0.141271
3   0.765487 -0.572645
4   0.993248  0.395417
5  -0.454272  0.357839
6  -0.438745  0.324409
7  -0.150585  0.158946
8   0.989886  0.139909
9   1.078010  0.232569
10  0.132604 -0.150200
11  0.939636  0.493141
12  0.054326 -0.321143
13  0.343658 -0.479216
14 -0.737618 -0.229674
15 -0.645702 -0.172073

In [14]:
df = pd.DataFrame(error)

In [15]:
df.to_csv('yy.csv', header=False, index=False)

In [16]:
import math
from sklearn.metrics import mean_squared_error
mse_true  = mean_squared_error(trains_labels, enen)
mse_true

0.2683257386338679

In [17]:

rmse = math.sqrt(mse_true)
rmse

0.5180016782153006

# fold 2

In [18]:
inputs = pd.read_csv('data/bursa2.csv',delimiter=',', header=None) #loading inputs from a different file 
print (inputs.shape)
targets = pd.read_csv('data/UTM2.csv',delimiter=',', header=None) # loading targets
print(targets.shape)
trains = pd.read_csv('data/Cass_f2.csv',delimiter=',', header=None) #loading inputs from a different file 
print (trains.shape)
trains_labels = pd.read_csv('data/aff_test2.csv',delimiter=',', header=None) # loading targets
print (trains_labels.shape)

(64, 4)
(64, 1)
(16, 2)
(16, 2)


In [19]:

bursa= inputs.to_numpy()
EnUTM = targets.to_numpy()
print (type(bursa))
print (type(inputs))
print (type(EnUTM))
print (EnUTM.shape)

<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
(64, 1)


In [20]:
A=bursa
At=A.T
At.shape
ATA = np.dot(At,A)
ATA
L = EnUTM
L.shape
ATL= np.dot(At,L)
ATL.shape

(4, 1)

In [21]:
from numpy.linalg import inv
m_inv=inv(ATA)*-1
m_inv
x2= -(np.dot(m_inv,ATL))
x2

array([[1.00025397e+00],
       [2.26383810e-04],
       [2.77489725e+05],
       [1.00001879e+07]])

In [22]:
a =x2[0]
a
b = x2[1]
b
c=x2[2]
d = x2[3]

In [23]:
t = trains.to_numpy()
t1 = t[:,0]*a

t2 = t[:,1]*b

t3 =  t[:,0]*b

t4 =  t[:,1]*a

In [24]:
east = c+ t1-t2

print (east)
north= d +t3+t4

print (north)

[265097.26270365 265265.68462061 265121.66954803 267215.19438915
 262776.4572494  263194.35798451 265499.76897455 261817.74727445
 263194.1823709  264982.36507306 265569.05795524 263251.43316888
 265435.632474   263531.43464073 264017.09160465 262166.39295015]
[9944095.84840657 9936518.55447491 9941732.26120784 9942304.04483376
 9942960.90473766 9940512.98603807 9944468.62166827 9938077.98433674
 9940076.55396488 9944587.52871274 9938718.89302251 9942928.29888955
 9935535.05836654 9936992.15490063 9936509.76580528 9941229.91654861]


In [25]:
ene1 = pd.DataFrame(east)
ene1.shape
#type(ene1)
ene2 = pd.DataFrame(north)
ene2.shape

(16, 1)

In [26]:
m =ene1.join(ene2, on= None, how ='right', lsuffix = '_left', rsuffix = '_right')
m.to_csv('y.csv', header=False, index=False)
ene = pd.read_csv('y.csv',delimiter=',', header=None, ) # loading targets
print(ene.shape)

(16, 2)


In [27]:
enen =ene.to_numpy()
type(enen)
error = trains_labels - enen
error

0         1
0  -0.462704  0.051593
1   0.315379  0.045525
2  -0.269548  0.038792
3  -0.294389  0.155166
4  -0.457249 -0.204738
5  -0.157985 -0.186038
6  -0.468975 -0.021668
7   0.052726 -0.284337
8  -0.182371 -0.153965
9  -0.565073 -0.028713
10  0.042045  0.106977
11 -0.433169 -0.098890
12  0.467526  0.141633
13  0.165359 -0.154901
14  0.308395 -0.065805
15 -0.292950 -0.216549

In [28]:
df = pd.DataFrame(error)
df.to_csv('yy.csv', header=False, index=False)

In [29]:
import math
from sklearn.metrics import mean_squared_error
mse_true  = mean_squared_error(trains_labels, enen)
mse_true

0.06961393272665407

In [30]:

rmse = math.sqrt(mse_true)
rmse

0.2638445237761324

# Fold 3

In [31]:
inputs = pd.read_csv('data/bursa3.csv',delimiter=',', header=None) #loading inputs from a different file 
print (inputs.shape)
targets = pd.read_csv('data/UTM3.csv',delimiter=',', header=None) # loading targets
print(targets.shape)
trains = pd.read_csv('data/Cass_f3.csv',delimiter=',', header=None) #loading inputs from a different file 
print (trains.shape)
trains_labels = pd.read_csv('data/aff_test3.csv',delimiter=',', header=None) # loading targets
print (trains_labels.shape)

(64, 4)
(64, 1)
(16, 2)
(16, 2)


In [32]:

bursa= inputs.to_numpy()
EnUTM = targets.to_numpy()
print (type(bursa))
print (type(inputs))
print (type(EnUTM))
print (EnUTM.shape)

<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
(64, 1)


In [33]:
A=bursa
At=A.T
At.shape
ATA = np.dot(At,A)
ATA
L = EnUTM
L.shape
ATL= np.dot(At,L)
ATL.shape

(4, 1)

In [34]:
from numpy.linalg import inv
m_inv=inv(ATA)*-1
m_inv
x3= -(np.dot(m_inv,ATL))
x3

array([[1.00024201e+00],
       [3.72232730e-04],
       [2.77480854e+05],
       [1.00001890e+07]])

In [35]:
a =x3[0]
a
b = x3[1]
b
c=x3[2]
d = x3[3]

In [36]:
t = trains.to_numpy()
t1 = t[:,0]*a

t2 = t[:,1]*b

t3 =  t[:,0]*b

t4 =  t[:,1]*a

In [37]:
east = c+ t1-t2

print (east)
north= d +t3+t4

print (north)

[263547.12400742 266734.85943701 263661.58384925 265163.85208158
 261839.93536094 263217.68349531 267171.75047735 267522.26378188
 264894.47942673 266845.41003672 267355.47372183 265069.67919375
 263008.28307967 262720.06398123 267073.91765575 263334.49029817]
[9938884.23653457 9934609.72011418 9939839.87559206 9937948.78413701
 9944501.48037955 9935836.59535631 9938195.89988549 9939015.43965876
 9939468.14446096 9937058.41621417 9935557.43789007 9943020.99560077
 9942917.21160778 9944286.81090394 9941141.98102875 9935073.35676074]


In [38]:
ene1 = pd.DataFrame(east)
ene1.shape
#type(ene1)
ene2 = pd.DataFrame(north)
ene2.shape

(16, 1)

In [39]:
m =ene1.join(ene2, on= None, how ='right', lsuffix = '_left', rsuffix = '_right')
m.to_csv('y.csv', header=False, index=False)
ene = pd.read_csv('y.csv',delimiter=',', header=None, ) # loading targets
print(ene.shape)

(16, 2)


In [40]:
enen =ene.to_numpy()
type(enen)
error = trains_labels - enen
error

0         1
0  -0.224007  0.063465
1  -0.259437 -0.020114
2  -0.183849  0.124408
3  -0.252082  0.015863
4  -0.035361  0.319620
5  -0.283495  0.104644
6  -0.150477  0.000115
7  -0.163782 -0.039659
8  -0.179427  0.055539
9  -0.210037 -0.016214
10 -0.273722 -0.037890
11  0.020806  0.104399
12 -0.083080  0.188392
13  0.036019  0.289096
14 -0.017656  0.018971
15 -0.390298  0.043239

In [41]:
df = pd.DataFrame(error)
df.to_csv('yy.csv', header=False, index=False)

In [42]:
import math
from sklearn.metrics import mean_squared_error
mse_true  = mean_squared_error(trains_labels, enen)
mse_true

0.029070380751911186

In [43]:

rmse = math.sqrt(mse_true)
rmse

0.17050038343625853

# aggregating the parameters

In [44]:
x_mean = np.mean( np.array([ x1, x2,x3 ]), axis=0 )
x_mean

array([[1.00024995e+00],
       [2.59682955e-04],
       [2.77487657e+05],
       [1.00001880e+07]])

In [45]:
a =x_mean[0]
b = x_mean[1]
c=x_mean[2]
d = x_mean[3]

# evaluating on training data

In [46]:

trains = pd.read_csv('data/train_Cass.csv',delimiter=',', header=None) #loading inputs from a different file 
print (trains.shape)
trains_labels = pd.read_csv('data/train_UTM.csv',delimiter=',', header=None) # loading targets
print (trains_labels.shape)

(48, 2)
(48, 2)


In [47]:
t = trains.to_numpy()
t1 = t[:,0]*a

t2 = t[:,1]*b

t3 =  t[:,0]*b

t4 =  t[:,1]*a

In [48]:
east = c+ t1-t2

print (east)
north= d +t3+t4

print (north)

[262058.45214538 266952.21807196 263425.56783929 261270.46198157
 266422.3647248  267140.92806788 267293.25133865 265739.32721691
 265088.86277206 265445.92702321 263168.22448825 267273.36974752
 262157.39298456 261519.6826928  262644.03644323 263424.65488817
 265097.11146112 265265.78496243 265121.59689514 267215.09429959
 262776.35310409 263194.33365734 265499.60370658 261817.80953657
 263194.17257395 264982.19792277 265569.08382688 263251.32820305
 265435.764876   263531.526175   264017.19724953 262166.34888033
 263546.91894747 266734.19853494 263661.48722607 265163.5545147
 261840.34891504 263217.13289892 267171.49655877 267522.10484781
 264894.35070137 266845.02554756 267354.92435855 265069.95163692
 263008.52758094 262720.46032339 267073.99447451 263333.85473954]
[9940059.49479442 9936008.80811675 9941625.32805405 9934567.61613264
 9933929.65874773 9943791.61489152 9943294.4623241  9941300.4124249
 9934062.20808381 9933383.6463543  9939149.02622751 9934501.12622723
 9939322.11640

In [49]:
ene1 = pd.DataFrame(east)
ene1.shape
#type(ene1)
ene2 = pd.DataFrame(north)
ene2.shape

(48, 1)

In [50]:
m =ene1.join(ene2, on= None, how ='right', lsuffix = '_left', rsuffix = '_right')
m.to_csv('y.csv', header=False, index=False)
ene = pd.read_csv('y.csv',delimiter=',', header=None, ) # loading targets
print(ene.shape)

(48, 2)


In [51]:
enen =ene.to_numpy()
type(enen)
error = trains_labels - enen
error

0         1
0  -0.152145 -0.194794
1   0.281928  0.291883
2  -0.267839 -0.028054
3   0.238018 -0.316133
4   0.435275  0.241252
5  -0.228068  0.185108
6  -0.251339  0.137676
7  -0.127217  0.087575
8   0.437228  0.091916
9   0.472977  0.153646
10 -0.024488 -0.026228
11  0.430252  0.273773
12 -0.092985 -0.116407
13  0.017307 -0.232622
14 -0.436443 -0.041568
15 -0.354888 -0.046474
16 -0.311461  0.091954
17  0.215038  0.049872
18 -0.196895  0.068856
19 -0.194300  0.117828
20 -0.353104 -0.091668
21 -0.133657 -0.096704
22 -0.303707  0.006789
23 -0.009537 -0.158944
24 -0.172574 -0.066376
25 -0.397923  0.017446
26  0.016173  0.110055
27 -0.328203 -0.001763
28  0.335124  0.136376
29  0.073825 -0.090917
30  0.202750 -0.019926
31 -0.248880 -0.090115
32 -0.018947 -0.100536
33  0.401465  0.208310
34 -0.087226 -0.034253
35  0.045485  0.041165
36 -0.448915 -0.080801
37  0.267101 -0.072383
38  0.103441  0.249407
39 -0.004848  0.242610
40 -0.050701  0.038543
41  0.174452  0.205331
42  0.275641  0.252892
43 -0.251637  0.079087
44 -0.327581 -0.068061
45 -0.360323 -0.010594
46 -0.094475  0.234012
47  0.245260 -0.114622

In [52]:
import math
from sklearn.metrics import mean_squared_error
mse_true  = mean_squared_error(trains_labels, enen)
mse_true

0.045890086485201764

In [53]:
rmse = math.sqrt(mse_true)
rmse

0.21421971544468488

In [54]:
error.to_csv('yy.csv', header=False, index=False)

# test data

In [55]:
t = test.to_numpy()
t1 = t[:,0]*a

t2 = t[:,1]*b

t3 =  t[:,0]*b

t4 =  t[:,1]*a

In [56]:
east = c+ t1-t2

print (east)
north= d +t3+t4

print (north)

[265479.63268674 265466.45009226 266757.44064509 265147.81910767
 262902.20444667 262235.55780287 265321.67263378 267280.33123777
 263065.96946917 266734.19853494 263661.48722607 261383.54424095
 267369.98661286 262405.28431505 265252.18410378 264410.06858907
 263466.5221532 ]
[9937546.34332985 9934421.66369382 9933159.68942373 9943952.43793152
 9941909.88557865 9934763.20087278 9939909.21485114 9940098.16733592
 9933393.05890143 9934609.4916896  9939840.03425305 9935610.35259574
 9933555.51678913 9944620.10602172 9940994.00731932 9944112.55030616
 9933486.11964671]


In [57]:
ene1 = pd.DataFrame(east)
ene1.shape
#type(ene1)
ene2 = pd.DataFrame(north)
ene2.shape

(17, 1)

In [58]:
m =ene1.join(ene2, on= None, how ='right', lsuffix = '_left', rsuffix = '_right')
m.to_csv('y.csv', header=False, index=False)
ene = pd.read_csv('y.csv',delimiter=',', header=None, ) # loading targets
print(ene.shape)

(17, 2)


In [59]:
enen =ene.to_numpy()
type(enen)
error = labels - enen
error

0         1
0   0.067313  0.156670
1   0.349908  0.136306
2   0.559355  0.310576
3  -0.319108  0.062068
4  -0.304447 -0.085579
5   0.342197 -0.200873
6  -0.072634  0.085149
7  -0.031238  0.232664
8   0.430531 -0.158901
9   0.401465  0.208310
10 -0.087226 -0.034253
11  0.155759 -0.252596
12  0.513387  0.383211
13 -0.384315 -0.106022
14 -0.184104  0.092681
15 -0.368589  0.049694
16  0.477847 -0.119647

In [60]:
import math
from sklearn.metrics import mean_squared_error
mse_true  = mean_squared_error(labels, enen)
mse_true

0.07397189854958529

In [61]:

rmse = math.sqrt(mse_true)
rmse

0.2719777537770052

In [62]:
error.to_csv('yy.csv', header=False, index=False)

In [68]:
df = pd.DataFrame(x_mean)
df.to_csv('parameter.csv', header=False, index=False)